# -*- coding: utf-8 -*-
"""WikiRandomizer071621v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10YFAGaKTyWcbSQB0ZOi6worMQbc8Pdia
"""

import requests
from bs4 import BeautifulSoup
from lxml import html as lh
import pandas as pd
import webbrowser

def status_check(r):
  if r.status_code == 200:
    return 1
  else:
    print("Failed!")
    return -1

def encoding_check(r):
  return(r.encoding)

def decode_content(r,encoding):
  return(r.content.decode(encoding))

for i in range(3):
  wiki = "https://en.wikipedia.org/wiki/Special:Random"
  response = requests.get(wiki)
  contents = decode_content(response, encoding_check(response))
  soup = BeautifulSoup(contents, "html.parser")
  txt_dump = soup.text
  index2 = txt_dump.find(" - Wikipedia")
  print("The title of the article is ","'",txt_dump[0:index2].lstrip(),"'")
  decision = str(input("Would you like to learn more about this random article? (Y/N) "))
  
  #cleaning the output for the program to convert to Wiki articles
  id = txt_dump[0:index2]
  id2 = " ".join(id.split())
  id3 = id2.replace(" ", "_")

  if decision == "Y":
    print("\nIf running this on a local machine, your browser will open up the article. \nIf running via Google Colab, or cloud-based, then the link is below.")
    #need to run a check of the webpage if it's accessible before opening browser
    if response.status_code == requests.codes.ok:
      webbrowser.open('https://www.wikipedia.org/wiki/%s' % id3, new=1)
      print("www.wikipedia.org/wiki/%s" % id3)
      #use Pandas to create a table of the references for the article
      #allLinks = soup.find(id="mw-content-text").find_all("a")
      #print(allLinks)
      break
    else:
      print("This article is unable to be reached. Try another article.")
      break
  elif decision == "N":
    if i < 2:
      dec2 = str(input("Okay, want to try another random article? (Y/N) "))
      if dec2 == "Y":
        continue
      elif dec2 == "N":
        print("Thank you for your interest! Have a wonderful day.")
        break
      else:
        print("Response not recognized. Please enter Y or N.")
        continue
    elif i == 2:
      print("Re-run the program if you are wanting more random articles.")
      break
  else:
    print("You didn't provide a proper response. Please enter Y or N.")
    break